
name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-207-67-252.sa-east-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            pwd
            ls -l
            /path/to/node --version
            /path/to/npm --version
            npm --version
            cd /home/ubuntu/frontend/WallDreams
            git pull origin develop
            /path/to/npm run build
            sudo systemctl restart nginx
