name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-207-67-252.sa-east-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            
            pwd
            ls -l
            
            # Verify node and npm versions
            /home/ubuntu/.nvm/versions/node/v20.13.1/bin/node --version
            /home/ubuntu/.nvm/versions/node/v20.13.1/bin/npm --version
            
            # Navigate to the project directory
            cd /home/ubuntu/frontend/WallDreams
            
            
            # Build the project
            /home/ubuntu/.nvm/versions/node/v20.13.1/bin/npm run build
            
            # Restart nginx service
            sudo systemctl restart nginx
