name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-207-67-252.sa-east-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend/WallDreams
            echo "Stashing local changes..."
            git stash -u
            echo "Pulling latest changes from develop branch..."
            git pull origin develop
            echo "Latest changes pulled."
            
            echo "Applying stashed changes..."
            git stash pop || true  # Ignorar erro se não houver stashes

            
            echo "Building the project..."
            if npm run build; then
              echo "Build successful."
            else
              echo "Build failed."
              exit 1
            fi

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            echo "Nginx restarted."

            echo "Deployment completed successfully."
